server:
  port: 8022
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ReD
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
