server:
  port: 8022
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/RemoteDoctor
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
